#!/bin/bash
set -euo pipefail

display=${1#:}
argsize="${5}x16"
size=${argsize}

cat <<EOF | tee {{ nonroot_supervisord_conf_dir }}/conf.d/Xvfb_x11vnc.conf > /dev/null
[program:Xvfb]
command=/usr/bin/Xvfb ":${display}" -screen 0 "${size}" -nolisten tcp
priority=1
[program:x11vnc]
command=/usr/bin/x11vnc -display "WAIT:${display}" -reopen -shared -localhost -rfbport "$(( 5900 + display ))" -rfbportv6 -1 -repeat -nopw -noxrecord
priority=2
autorestart=true
EOF

trap 'kill $(pgrep supervisord)' TERM INT
supervisord -n -c {{ nonroot_supervisord_conf_dir }}/supervisord.conf &
pid=$!
wait "${pid}"
trap - TERM INT
wait "${pid}"
